/*
 * (C) 2014 theMobies, LLC.  All Rights Reserved.  Confidential Information of theMobies, LLC.
 */

package exceptions;

/**
 * Represents application's internal error code.
 */
public enum ErrorCode
{
    UNKNOWN_ERROR_CODE(0),

    NOT_VALIDATED_ERROR_CODE(1001),

    NOT_FOUND_ERROR_CODE(1002),

    NOT_AUTHENTICATED_ERROR_CODE(1003),

    CREATION_USER_ERROR_CODE(1004),

    NOT_CREATED_ERROR_CODE(1005),

    FIELD_NOT_FOUND_ERROR_CODE(1006),

    VALIDATION_EXECUTION_ERROR_CODE(1007),

    NOT_DELETED_ERROR_CODE(1008),

    EXTENDED_LINE_ITEM_NOT_FOUND_ERROR_CODE(1009),

    ALREADY_DELETED_ERROR_CODE(1010),

    NOT_UPDATED_ERROR_CODE(1011), RESOURCE_CONFLICT_ERROR_CODE(1012),

    CONFIGURATION_ERROR_CODE(1013),

    NOT_AUTHORIZED_ERROR_CODE(1014),

    PASSWORD_EXPIRED_ERROR_CODE(1015),

    BAD_REQUEST_ERROR_CODE(4001),

    CONFLICT_ERROR_CODE(4002),

    JSON_PARSE_ERROR_CODE(5001),

    JSON_SCHEMA_PROCESSING_ERROR_CODE(5002),

    JSON_SCHEMA_VALIDATION_ERROR_CODE(5003),

    UNSUPPORTED_ERROR_CODE(6001),

    AQL_PARSING_ERROR_CODE(7001),

    FILTER_FIELD_NOT_FOUND_ERROR_CODE(7002),

    FILTER_FIELD_TYPE_MISMATCH_ERROR_CODE(7003),

    FILTER_FIELD_INVALID_FORMAT_ERROR_CODE(7004),

    ADDITION_ROLE_ERROR_CODE(8001),

    ADDITION_PERMISSION_ERROR_CODE(8002),

    DATABASE_ERROR_CODE(8003),

    DELETION_PERMISSION_ERROR_CODE(8004),

    DELETION_ROLE_ERROR_CODE(8005),

    AUDIT_ERROR_CODE(9001),

    RESOURCE_UNAVAILABLE_ERROR_CODE(10001),

    EXTERNAL_SERVICE_PROBLEM_ERROR_CODE(10002),

    DATE_ROLL_ERROR_CODE(11001),

    PATCH_UNSUPPORTED_INSTRUCTION_ERROR_CODE(12001),

    PATCH_VALIDATION_ERROR_CODE(12002),

    PATCH_INVALID_PATH_FORMAT(12003),

    PATCH_INVALID_FIELD_NAME(12004),

    PATCH_ILLEGAL_FIELD(12005),

    PATCH_REQUEST_FORMAT_MISMATCH(12006),

    UPDATE_NULL_ARRAY(12011),

    UPDATE_INVALID_ARRAY_INDEX(12012),

    NO_SUB_SCHEMAS_MATCHED_PARTIAL_UPDATE_REQUEST(12013),

    AMBIGUOUS_SUB_SCHEMAS_MATCHED_PARTIAL_UPDATE_REQUEST(12014),

    INVALID_PAGINATION_PARAMETERS(13001),

    MISSING_REQUIRED_FIELDS(13002),

    INVALID_SORTING_PARAMETER(14001),

    SORTING_FIELD_NOT_FOUND(14002),

    SORTING_FIELD_IS_NOT_SORTABLE(14003),

    SORTING_FIELD_DUPLICATED(14004),

    DATABASE_ACCESS_ERROR(4000);

    /**
     * Application's internal error code.
     */
    private Integer code;

    ErrorCode(Integer code)
    {
        this.code = code;
    }

    public Integer getCode()
    {
        return code;
    }
}
